project:
  type: website
  output-dir: docs

website:
  title: Ancient Oceans
  site-url: https://explore.ancientoceans.org
  description: "Scroll through Earth's Oceans"
  search: false
  navbar:
    title: Ancient Oceans
    pinned: true
    collapse: true
    foreground: "white"
    background: "#201c2f"
    right:
      - text: "Contribute"
        href: "https://forms.gle/42fqXep3b8pf8KMk8"
        target: "_blank"
      - text: "Inspiration"
        href: "https://neal.fun/deep-sea/"
        target: "_blank"
  page-footer: 
    foreground: "white"
    background: "#201c2f"
    left: "Copyright 2025, Lewis A. Jones" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    css: style.css
    toc: false
    smooth-scroll: false
    link-external-newwindow: true

